version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test
      - JWT_KEY=key12345
    volumes:
      - .:/app

volumes:
  mongodb_data_container: