services:
  k6:
    build: .
    environment:
      - ENVIRONMENT=local
      - K6_OUT=xk6-influxdb=http://0.0.0.0:8086
      - K6_INFLUXDB_ORGANIZATION=test
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_INSECURE=true
        # NOTE: This is an Admin token, it's not suggested to use this configuration in production.
        # Instead, use a Token with restricted privileges.
      - K6_INFLUXDB_TOKEN=fvWb_ZrfVaWP4uWa1_Qv98u5_q2y4uuSig2Qrv_ReVl8gWOJpJfOt6RJP7ZEbJ3PvDKIVQWM4F94Llaac5380g==
    network_mode: "host"
    stdin_open: true
    tty: true
    working_dir: /scripts
    volumes:
      - ./k6-scripts:/scripts
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdbtest
      - DOCKER_INFLUXDB_INIT_PASSWORD=test1234
      - DOCKER_INFLUXDB_INIT_ORG=test
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=fvWb_ZrfVaWP4uWa1_Qv98u5_q2y4uuSig2Qrv_ReVl8gWOJpJfOt6RJP7ZEbJ3PvDKIVQWM4F94Llaac5380g==
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
