services:
  k6:
    image: grafana/k6
    environment:
      - BASE_URL="http://localhost:3001"
    network_mode: "host"
    stdin_open: true
    tty: true
    working_dir: /scripts
    volumes:
      - ./k6-scripts:/scripts
