version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh # run a script to set up Heroku
      - run:
          command: |
            git subtree push --prefix demos/run-logger heroku main
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart
            heroku ps:wait -a run-logger-demo
  clear_db:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: |
            yarn
            yarn clear:db
  smoke_test:
    docker:
      - image: sjoedwards1/k6-v2-influxdb
    environment:
      - K6_OUT=xk6-influxdb=https://eu-central-1-1.aws.cloud2.influxdata.com
      - K6_INFLUXDB_ORGANIZATION=samuel.j.o.edwards@gmail.com
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Execute smoke tests
          command: K6_INFLUXDB_TOKEN=$INFLUXDB_TOKEN k6 run k6-scripts/demos/run-logger/smoke.js
  load_test:
    docker:
      - image: sjoedwards1/k6-v2-influxdb
    environment:
      - K6_OUT=xk6-influxdb=https://eu-central-1-1.aws.cloud2.influxdata.com
      - K6_INFLUXDB_ORGANIZATION=samuel.j.o.edwards@gmail.com
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Execute smoke tests
          command: K6_INFLUXDB_TOKEN=$INFLUXDB_TOKEN k6 run k6-scripts/demos/run-logger/load.js




workflows:
  version: 2
  deploy-and-test:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
      - smoke_test
          requires:
            - deploy
      - load_test
          requires:
            - smoke_test
