version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh # run a script to set up Heroku
      - run:
          command: |
            git subtree push --prefix demos/run-logger heroku main
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart
            heroku ps:wait -a run-logger-demo
  clear_db:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: |
            yarn
            yarn clear:db
  smoke_test:
    docker:
      - image: sjoedwards1/k6-v2-influxdb
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Execute smoke tests
          command: |
            echo 'export K6_OUT=xk6-influxdb=https://eu-central-1-1.aws.cloud2.influxdata.com' >> $BASH_ENV
            echo 'export K6_INFLUXDB_ORGANIZATION=samuel.j.o.edwards@gmail.com' >> $BASH_ENV
            echo 'export K6_INFLUXDB_BUCKET=k6' >> $BASH_ENV
            echo 'export K6_INFLUXDB_INSECURE=true' >> $BASH_ENV
            echo 'export K6_INFLUXDB_TOKEN=$INFLUXDB_TOKEN' >> $BASH_ENV
            k6 run k6-scripts/demos/run-logger/smoke.js



workflows:
  version: 2
  deploy-and-test:
    jobs:
      # - deploy:
      #     filters:
      #       branches:
      #         only: main
      - smoke_test
      # - grafana/k6:
      #     name: load_test
      #     script: k6-scripts/demos/run-logger/load.js
      #     requires:
      #       - smoke_test
      # - clear_db:
      #     requires:
      #       - load_test