version: 2.1

orbs:
  grafana: grafana/k6@1.1.3

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh # run a script to set up Heroku
      - run:
          command: |
            git subtree push --prefix demos/run-logger heroku main
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart
  smoke_test:
    steps:
        jobs:
          - checkout
          - grafana/k6:
              script: k6-scripts/run-logger/smoke.js


workflows:
  version: 2
  deploy-and-test:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
      - smoke_test:
          requires:
            - deploy
